In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

C:\Rexline\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done  40 tasks      | elapsed:    5.2s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    5.8s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [9]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mse', 'max_features': 'auto', 'splitter': 'random'}:

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.024320,0.006596,0.003331,4.716513e-04,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.700165,0.662972,0.709006,0.690715,0.019946,4
1,0.010322,0.001707,0.003665,9.425721e-04,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.686123,0.738131,0.778930,0.734395,0.037980,1
2,0.015993,0.010608,0.004330,1.247938e-03,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.739369,0.602589,0.715836,0.685931,0.059710,7
3,0.007662,0.000473,0.004332,9.427412e-04,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.607256,0.702002,0.581726,0.630328,0.051742,14
4,0.009662,0.001249,0.004329,1.243073e-03,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.643015,0.501218,0.740625,0.628286,0.098291,15
5,0.006996,0.000816,0.002999,8.778064e-07,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.703937,0.657917,0.652551,0.671468,0.023063,10
6,0.092944,0.016865,0.002999,5.150430e-07,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.685855,0.718158,0.672326,0.692113,0.019227,3
7,0.057633,0.008173,0.003332,4.708084e-04,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.685008,0.697324,0.679919,0.687417,0.007307,6
8,0.072291,0.005433,0.004999,2.159428e-03,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.586963,0.674923,0.610163,0.624016,0.037222,16
9,0.037979,0.005712,0.012659,1.296243e-02,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.667252,0.748414,0.759590,0.725085,0.041148,2
10,0.061298,0.024943,0.013659,1.437515e-02,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.674376,0.591573,0.587658,0.617869,0.039989,17
11,0.032648,0.002867,0.009328,7.582301e-03,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.761832,0.551799,0.669603,0.661078,0.085957,11
12,0.010994,0.000815,0.002999,4.899036e-07,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.704323,0.653902,0.691182,0.683136,0.021356,8
13,0.015989,0.009923,0.006330,2.052941e-03,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.654688,0.711171,0.703009,0.689623,0.024926,5
14,0.011327,0.004711,0.002998,5.947204e-07,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.734240,0.677541,0.627309,0.679697,0.043681,9
15,0.014658,0.007582,0.004330,4.706960e-04,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.654279,0.639211,0.655789,0.649759,0.007484,12
16,0.017323,0.013218,0.002999,2.973602e-07,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.669596,0.574135,0.582186,0.608639,0.043228,18
17,0.007663,0.000471,0.003998,8.153669e-04,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.655366,0.612117,0.652964,0.640149,0.019846,13

In [11]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:45
BMI:45
Children:3
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [12]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[46151.1245]